version: '3.4'

services:
  alterego.api:
    image: ${DOCKER_REGISTRY-}alteregoapi
    build:
      context: .
      dockerfile: AlterEgo.API/Dockerfile
    depends_on:
     - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1"
        ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"