version: '3.4'

services:
  alterego.api:
    image: ${DOCKER_REGISTRY-}alteregoapi
    build:
      context: .
      dockerfile: AlterEgo.API/Dockerfile
    ports:
     - "80:80"
     - "443:443"
    environment:
     - "ASPNETCORE_ENVIRONMENT=Production"
     - "ASPNETCORE_URLS=https://+:443;http://+:80"
    depends_on:
     - db
     - seq
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1"
        ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"
  seq:
    image: "datalust/seq:latest"
    environment:
       ACCEPT_EULA: "Y"
    ports:
     - "5391:80"