version: '3.4'

services:
  alterego.api:
    image: ${DOCKER_REGISTRY-}alteregoapi
    build:
      context: .
      dockerfile: AlterEgo.API/Dockerfile
    ports:
     - "80:80"
     - "443:443"
    environment:
     - "ASPNETCORE_ENVIRONMENT=Docker"
     - "ASPNETCORE_URLS=https://+:443;http://+:80"
     - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
     - ~/.aspnet/https:/https:ro
     - /var/run/docker.sock:/var/run/docker.sock
     - ./files/images:/app/files/images
     - ./files/output:/app/files/output
     - ./files/temp:/app/files/temp
     - ./files/videos:/app/files/videos
    depends_on:
     - db
     - seq
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1"
        ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s
  seq:
    image: "datalust/seq:latest"
    environment:
       ACCEPT_EULA: "Y"
    ports:
     - "5391:80"